%YAML:1.0
---
image_width: 1280
image_height: 720
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: f
   data: [ 3.69502083e+02, 0., 6.40000000e+02, 0., 3.69502083e+02,
       3.60000000e+02, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: f
   data: [ 0., 0., 0., 0., 0. ]
