distance_x: 0.87
distance_z: 1.92

gamma: 0.314
half_theta_receiver: 1.046
half_theta_transmitter: 1.57

update_rate: 100

intensity_topics:
  - '/infraoptical/tag/iris_bottom_fpv/diode_pair/diode0'
  - '/infraoptical/tag/iris_bottom_fpv/diode_pair/diode1'
  - '/infraoptical/tag/iris_bottom_fpv/diode_pair/diode2'
  - '/infraoptical/tag/iris_bottom_fpv/diode_pair/diode3'